In [6]:
import numpy as np
a = np.array([1, 2, 3])
print("a[0:2]：", a[0:2])
print("a[1:]：", a[1:])
print("a[-2:]: ", a[-2:])
print(a[:-2])
print(a[-2])
type(a[-2])

a[0:2]： [1 2]
a[1:]： [2 3]
a[-2:]:  [2 3]
[1]
2


numpy.int32

In [7]:
a = np.array([
[1,2,3,4],
[5,6,7,8],
[9,10,11,12]
])

print(a[a>7])

[ 8  9 10 11 12]


In [9]:
l = [150, 166, 183, 170]
for i in l:
    i += 3
print(l)

[150, 166, 183, 170]


In [11]:
a = np.array([150, 166, 183, 170])
print(a + 3)
a += 3
print(a)

[153 169 186 173]
[153 169 186 173]


In [13]:
a = np.array([150, 166, 183, 170])
print("累乘：", a.prod())
print("总数：", a.size)   
                 
a = np.array([0, 1, 2, 3])

print("非零总数：", a.count_nonzero())


累乘： 774639000
总数： 4


AttributeError: 'numpy.ndarray' object has no attribute 'count_nonzero'

In [14]:
import numpy as np

a = np.array([1,2,3,4,5,6])
a_2d = a[np.newaxis, :]
print(a.shape, a_2d.shape)

(6,) (1, 6)


In [15]:
print(a_2d)

[[1 2 3 4 5 6]]


In [16]:
a = np.array([1,2,3,4,5,6])
a_none = a[:, None]
a_expand = np.expand_dims(a, axis=1)
print(a_none.shape, a_expand.shape)

(6, 1) (6, 1)


In [19]:
a = np.array([1,2,3,4,5,6]).reshape([2, 3])
aT1 = a.T
aT2 = np.transpose(a)
print(a)

print("aT1 is")
print(aT1)
print(aT2)


[[1 2 3]
 [4 5 6]]
aT1 is
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [20]:
#特征 a 的数据和特征 b 的数据合并
feature_a = np.array([1,2,3,4,5,6])
feature_b = np.array([11,22,33,44,55,66])
c_stack = np.column_stack([feature_a, feature_b])
print(c_stack)

[[ 1 11]
 [ 2 22]
 [ 3 33]
 [ 4 44]
 [ 5 55]
 [ 6 66]]


In [21]:
sample_a = np.array([0, 1.1])
sample_b = np.array([1, 2.2])
c_stack = np.row_stack([sample_a, sample_b])
print(c_stack)

[[0.  1.1]
 [1.  2.2]]
